spring.application.name=gateway

server.port=${SERVER_PORT}

mynimbus.url=${MYNIMBUS_BASE_URL}

spring.cloud.gateway.routes[0].id=backend
spring.cloud.gateway.routes[0].uri=${MYNIMBUS_BASE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/app/public/**,/app/deploy/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1