spring.application.name=gateway
server.port=8080

# Backend URL
mynimbus.url=http://localhost:8081

# Backend route only
spring.cloud.gateway.routes[0].id=backend
spring.cloud.gateway.routes[0].uri=${mynimbus.url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/app/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Disable default discovery
spring.cloud.gateway.discovery.locator.enabled=false

# Logging
logging.level.com.infra.gateway=DEBUG